# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_views', '0003_auto_20190429_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='movie'),
        ),
    ]
