# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_view', '0004_auto_20190509_1645'),
        ('shop_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=2000, verbose_name='评论的内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论的时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_view.GoodsDetail', verbose_name='被评论的商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论商品的用户')),
            ],
        ),
    ]
