# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_views', '0004_auto_20190430_0247'),
        ('movie_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=2000, verbose_name='评论的内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论的时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_views.MovieDetail', verbose_name='被评论的电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论电影的用户')),
            ],
        ),
    ]
