# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=1000, verbose_name='商品价格')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=255, verbose_name='电影类型的描述')),
            ],
        ),
    ]
