# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_view', '0002_delete_goodskind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='电影类型')),
                ('desc', models.CharField(max_length=255, verbose_name='电影类型的描述')),
            ],
        ),
    ]
