# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_view', '0003_goodskind'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='kind',
            field=models.ManyToManyField(to='shop_view.GoodsKind'),
        ),
        migrations.AlterField(
            model_name='goodskind',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='商品类型的描述'),
        ),
        migrations.AlterField(
            model_name='goodskind',
            name='name',
            field=models.CharField(max_length=255, verbose_name='商品类型'),
        ),
    ]
